# Generated by Django 4.1.2 on 2022-10-16 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("middle_name", models.CharField(blank=True, max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("email", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "data",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 10, 17, 0, 17, 0, 245864)
                    ),
                ),
                ("origin", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
